default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: print_api
  host: 107.170.194.195
  port: 5432
  username: sam
  password: <%= ENV['DIGITAL_OCEAN_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default
  database: print_api_test

production:
  <<: *default

